'use client';

import { useCallback } from 'react';
import { zipSync, strToU8 } from 'fflate';
import type { AssistantSummaryContent, LanguageType } from '@/lib/voiceforge-api';

interface DownloadZipOptions {
  code: string;
  language: LanguageType;
  summary?: AssistantSummaryContent | null;
  projectName?: string;
}

export function useDownloadZip() {
  return useCallback(({ code, language, summary, projectName }: DownloadZipOptions) => {
    if (!code.trim()) return;

    const slug = (projectName ?? 'voiceforge-project')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    const codeFilename = language === 'html' ? 'index.html' : 'main.py';

    // Build README content from summary if available
    const readmeLines: string[] = [
      `# ${projectName ?? 'VoiceForge Project'}`,
      '',
    ];
    if (summary) {
      readmeLines.push(
        '## What it does',
        summary.what_it_does,
        '',
        '## Components',
        summary.components,
        '',
      );
      if (summary.flow) {
        readmeLines.push('## Flow', summary.flow, '');
      }
    }
    if (language === 'python') {
      readmeLines.push('## Run', '```bash', `python ${codeFilename}`, '```', '');
    } else {
      readmeLines.push('## Run', `Open \`${codeFilename}\` in a browser.`, '');
    }
    readmeLines.push(`_Generated by VoiceForge — ${new Date().toLocaleDateString()}_`);

    const files = {
      [`${slug}/${codeFilename}`]: strToU8(code),
      [`${slug}/README.md`]: strToU8(readmeLines.join('\n')),
    };

    const zipped = zipSync(files, { level: 6 });
    // Copy into a fresh ArrayBuffer to satisfy the Blob constructor's type constraints
    const blob = new Blob([new Uint8Array(zipped)], { type: 'application/zip' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `${slug}.zip`;
    a.click();

    // Clean up object URL after download starts
    setTimeout(() => URL.revokeObjectURL(url), 10_000);
  }, []);
}
